# Generated by Django 4.0.2 on 2022-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('updatedOn', models.DateTimeField()),
                ('added', models.DateTimeField()),
                ('results', models.TextField()),
            ],
        ),
    ]
