# Generated by Django 4.0.2 on 2022-09-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cool_fts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchData',
        ),
    ]
