# Generated by Django 4.0.2 on 2022-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trailerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updatedOn', models.DateTimeField()),
                ('trailer', models.CharField(max_length=2000)),
            ],
        ),
    ]
