# Generated by Django 4.0.2 on 2022-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_trailerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdb',
            name='imdbID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
